name: ci

on:
    pull_request:
      branches:
        - main
    push:
      branches:
        - main

jobs:
    cache_dependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Cache Maven dependencies
              uses: actions/cache@v3
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  ${{ runner.os }}-maven-

    build:
        name: Maven build
        runs-on: ubuntu-latest
        steps:
            
            - name: Checkout Code
              uses: actions/checkout@v4
            

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '21'
      

            - name: Clean Verify Maven
              run: mvn clean verify